### ISSUE TITLE
I want to get contact details of the institutions from the dashboard So that I can communicate with them easily

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#108]
# Task Description:
This task associated with enabling BQA reviewer to find contact details (university email) in the dashboard for easier communication.

### 1. Requirements:

- frontend only.

### 2. Dependencies:
- none.

### 3. Pages: 
- BqaDash1.tsx
- BqaDash2.tsx

**Comment by Mrymk02** [comment]
add this to your local clone :

git fetch origin
git checkout 108-I-want-to-get-contact-details-of-the-institutions-from-the-dashboard-so-that-i-can-communicate-with-them-easily

**Comment by Mrymk02** [comment]
added contact email in the dashboard.

**Comment by Mrymk02** [comment]
added contact email in both Dash 1 and Dash 2
