### ISSUE TITLE
Do the processing workflow for summaries and assessment.

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#117]
Design an API that given an input file (it could be a path on S3 of a file that is already uploaded), will trigger AI workflow processing (Amazon Bedrock, Jumpstart) and then stores the results in a database.

**Comment by Mrymk02** [comment]
will add a description

**Comment by Mrymk02** [comment]
I am expected to communicate with Fatima Janahi, Maryam Alsaad and Fatima Marhoon to complete the task.

**Comment by Mrymk02** [comment]
switch to branch :
git fetch origin
git checkout 117-do-the-processing-workflow-for-summaries-and-assessment

**Comment by Mrymk02** [comment]
created a table to store summary results from Jumpstar AI model

it has the following attributes:
* standardName
* indicatorName
* fileUrl : store path of the file from the s3 bucket
* fileName
* summaryResults

**Comment by Mrymk02** [comment]
API Done in #118
