### ISSUE TITLE
Iteration 5 Architecture

### ISSUE THREAD

**Issue by cerashdan** [bahrain-bp/bqa-genai-challenge#119]

**Comment by cerashdan** [comment]
Add the photo for current architecture goal for iteration 5

**Comment by FatemaMarhoon** [comment]
> Add the photo for current architecture goal for iteration 5



![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/118673837/89b3beb1-1c76-4852-a4e6-3ca30fc76e3e)

**Comment by cerashdan** [comment]
This is your most important task of this sprint, you can't build, what you did not plan for. 

@FatemaMarhoon @AmjadShubbar @Mrymk02 @ayshu2001 @MaryamAlsaad @FatimaJ20

**Comment by cerashdan** [comment]
1. The workflow of generating summary or assessment. (input: files, output: summary/score) 
2. Mock APIs to accelerate front-end development , build the actual APIs.

**Comment by FatemaMarhoon** [comment]
![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/118673837/91971136-c302-4a22-99a1-09fe0cdd0cc1)

**Comment by FatimaJ20** [comment]
![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/145936933/99154dc3-84d5-4d37-a64a-7ce889ddde08)

@cerashdan Final architecture 

https://drive.google.com/file/d/1Uuj00y0VjTWz0WcPkNXpr283t5bG1zWJ/view?usp=sharing
Just incase it's in page-2-final
