### ISSUE TITLE
Connecting Cognito to the S3 upload

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#131]
When the reviewer creates a university, a folder for it gets created in  the uni-artifact bucket.
the folder structure is :  UniversityName/Logo 
The University name folder should be used in the S3 upload, so that each university uploads in their own folder.

**Comment by FatimaJ20** [comment]
This task is done, I only need to confirm one extra thing and then merge it to the main.
