### ISSUE TITLE
Display the Logo

### ISSUE THREAD

**Issue by FatimaJ20** [bahrain-bp/bqa-genai-challenge#162]

**Comment by MaryamTaraif** [comment]
@FatimaJ20 and I worked on the code for both the backend and frontend. After several attempts, we discovered that the logo in S3 was corrupted. I then uploaded the correct logo and modified the code accordingly to complete the task.

**Comment by FatimaJ20** [comment]
The logos are displayed in BQA dash1 but not yet displayed as the user profile photo
