### ISSUE TITLE
Floating Button for user guidance

### ISSUE THREAD

**Issue by Mrymk02** [bahrain-bp/bqa-genai-challenge#281]
Create the floating button and the page for both users where they can see the steps and process.

**Comment by FatimaJ20** [comment]
git fetch origin
git checkout 281-floating-button-for-user-guidance

**Comment by FatimaJ20** [comment]
https://github.com/bahrain-bp/bqa-genai-challenge/assets/145936933/16880567-83d0-43a6-a90b-5d5b40d95014

- videos and text is left, not to mention css.
