### ISSUE TITLE
Notifications using SES

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#34]
This task is associated with the creation of email notification system for missing or incorrect content of a file uploaded.

This solution uses :
-	Amazon S3 (for storing the bucket).
- 	AWS Lambda (trigger lambda to send the notification). 
-	Amazon SES (Simple Email Service).

A dummy page is done for uploading to the bucket and once uploaded it will be checked by SageMaker for the trigger

**Comment by maalsaegh** [comment]
@Mrymk02 What's the update on this task? This should have been closed from the last iteration

**Comment by cerashdan** [comment]
#99 solved in
