### ISSUE TITLE
User management + Authorization

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#38]
- BQA Reviewer can preview all universities, and add new university email, name, and logo. (Email and name can be added successfully, only adding logo is left, I faced some problems uploading the logo to S3 bucket )
- Forgot password, and change password pages are added.
- Displaying the logo will be in a separate task

**Comment by MaryamAlsaad** [comment]
BQA Reviewer can preview all universities, and  add new university. Forgot password, change password pages are added.
