### ISSUE TITLE
comment feedback from BQA frontend

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#39]
# Task Description:

The goal of this task is to enable the BQA reviewer to add comments on files that have been uploaded for the Officer to see. Comments will be linked to files using unique identifiers. So that when retrieving each file, the file summaries and comments associated with it, will also be fetched.

This task requires:

1. frontend
2. backend

Dependencies:
 #43 (automated summaries for University Officer) - follows same approach.

**Comment by ayshu2001** [comment]
@MaryamAlsaad is working on retrieving the summaries for the files upload, the retrieval of comments needs to follow the same approach with using file key to show comments for the file.

**Comment by Mrymk02** [comment]
![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/74730385/b0c17141-2506-4338-a8e2-fc57592bb332)

**Comment by Mrymk02** [comment]
## Error:

![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/74730385/5dc8c54f-e858-42c7-9b96-cf19086eabd3)

![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/74730385/90e1bcfd-1f24-4846-a846-cf7fd7e9ac21)



## Fix:

`npm install @rollup/rollup-win32-x64-msvc
`

**Comment by Mrymk02** [comment]
created a new branch because I'm guessing the previous one is corrupted

switching to the branch:

```
git fetch origin
git checkout 39--comment-feedback-frontend
```

**Comment by Mrymk02** [comment]
@FatimaJ20 @MaryamAlsaad 

I added the email thingie you can modify it as u wish 💕
and do testing please
