### ISSUE TITLE
maryamT_feature_indexPage

### ISSUE THREAD

**Issue by MaryamTaraif** [bahrain-bp/bqa-genai-challenge#4]

**Comment by MaryamTaraif** [comment]
added my name in App.tsx

**Comment by FatemaMarhoon** [comment]
pull request #4 reviewed by @FatemaMarhoon

**Comment by FatemaMarhoon** [comment]
pull request https://github.com/bahrain-bp/bqa-genai-challenge/issues/4 reviewed by @FatemaMarhoon
