### ISSUE TITLE
additional documents request SES

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#41]
This task is enables BQA reviewer to send email notifications to the Educational Institute with required message ( when needed ). 

Notes : 
- It is related to a previous task ( #34 ). 
- It is different than the task in terms of having the user be able to include a message.

**Comment by Mrymk02** [comment]
It is related to a previous task ( #34 ).

**Comment by Mrymk02** [comment]
add this to your local clone :

git fetch origin
git checkout 41-MaryamK-additional-documents-request-ses

**Comment by cerashdan** [comment]
Attach the actual branch of work, not a dummy branch

**Comment by Mrymk02** [comment]
Trying to fix this error :

Failed to load resource: the server responded with a status of 500 ()
RequestAdditional.tsx:99 

Network Error: SyntaxError: Unexpected token 'T', "This funct"... is not valid JSON
sendEmail @ RequestAdditional.tsx:99

**Comment by Mrymk02** [comment]
@cerashdan @



![Image](https://github.com/bahrain-bp/bqa-genai-challenge/assets/74730385/b3bf1f09-4b75-4907-b4b4-b2fdbdeb4333)



I need help this task should've been done weeks ago but errors continued to appear, I've solved all of them but couldn't find a solution for this one.

I used the same lambda and api as Aysha that works fine for her in this task #99 , I also tried to test her branch at my stage the exact same error shows up. what should i do?

the pages that could be the cause of the error are : 
* stacks\EmailAPIStack.ts
* packages\functions\src\send-email.ts
* packages\frontend\src\pages\BqaRequestPage.tsx

**Comment by cerashdan** [comment]
500 internal server error means the API is not working properly or you are giving the wrong parameters. 

Troubleshoot your API by viewing the cloudwatch logs, or review the API code. Nothing to be done from UI side unless you are giving the wrong input. 

Bring the team member who developed the API to help you give it the right input if that is the case.

**Comment by cerashdan** [comment]
Please list all the API parameters/inputs, the path and the expected return value.

Unit test your API using an API tool like POSTMAN

**Comment by Mrymk02** [comment]
Thank you so much I'll do that in sha allah

**Comment by maalsaegh** [comment]
Moved back to in progress since it's not working yet

**Comment by Mrymk02** [comment]
It is finally working well
