### ISSUE TITLE
automated summaries for BQA reviewer 

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#43]
Create an interface that will contain the summaries of the uploaded documents. There would be 2 views

A view for BQA reviewer, where he can see the summaries of uploaded documents across all universities.
A view for a single university.
This implementation should include an API, a user interface (page/s), database integration and a workflow to do the assessment.

**Comment by cerashdan** [comment]
@MaryamAlsaad add description here please

**Comment by cerashdan** [comment]
@AmjadShubbar  @FatemaMarhoon @MaryamTaraif  Provide her with Mock API so she can finish the full page with the right format returned from the API. 

Create a task that will implement the API and mention here.

**Comment by cerashdan** [comment]
@MaryamAlsaad  attach a branch
